---
title: "Project"
author: "Spencer Hamilton, Chris Gordon, and Dan Sumsion"
format: pdf
editor: visual
---

```{r}
library(vroom)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyverse)
```

```{r}


movie <- vroom("TMDB_movie_dataset_v11.csv")


cutoff_year <- 2000

movie <- movie |>
  filter(status == "Released",
         vote_average > 0) |>
  mutate(release_date = as.Date(release_date),
         release_year = year(release_date),
         movie_age = ifelse(release_year <= cutoff_year, "Old", "New"))



movie$year_bin <- cut(movie$release_year,
                      breaks = seq(floor(min(movie$release_year, na.rm = TRUE) / 10) * 10,
                                   ceiling(max(movie$release_year, na.rm = TRUE) / 10) * 10, 
                                   by = 10),
                      right = FALSE,
                      labels = paste0(seq(floor(min(movie$release_year, 
                                                    na.rm = TRUE) / 10) * 10,
                                          ceiling(max(movie$release_year, 
                                                      na.rm = TRUE) / 10) * 10 - 10,
                                          by = 10),
                                      "s")) # Format labels as "1990s","2000s", etc.



summary(movie)

```

```{r}
ggplot(movie, aes(x = release_year)) +
  geom_histogram(binwidth = 5, fill ="blue", color ='black') +
  labs(title ="Distribution of Movie Release Years", x = 'Year', y = 'count')


```

```{r}
# Now you can plot the distribution of ratings
ggplot(movie, aes(x = vote_average)) +
  geom_histogram(binwidth = 1, fill ="blue", color = 'black') +
  labs(title ="Distribution of Movie Ratings", x ="Rating", y ="Count")
```

```{r}
cat(quantile(movie$release_year, 0.3, na.rm = TRUE))
```

```{r}
cat(ecdf(movie$release_year)(2000))
cat(table(movie$year_bin))
```
